-- migration: create extensions and enum types
-- purpose: set up required postgresql extensions and custom enum types for the flashcards application
-- affected: database extensions, custom types
-- special considerations: this migration must run first as other migrations depend on these types

-- enable citext extension for case-insensitive text columns (used in decks.name)
-- citext provides case-insensitive character string type while preserving original case
create extension if not exists citext;

-- flashcard_source enum: tracks the origin of a flashcard
-- values:
--   - 'ai_full': fully generated by ai, unmodified
--   - 'ai_edited': generated by ai but subsequently edited by user
--   - 'manual': created manually by user
create type flashcard_source as enum ('ai_full', 'ai_edited', 'manual');

-- space_repetition_status enum: tracks spaced repetition review status for flashcards
-- values:
--   - 'OK': flashcard reviewed successfully
--   - 'NOK': flashcard reviewed but user had difficulty
--   - 'not_checked': flashcard not yet reviewed (default state)
create type space_repetition_status as enum ('OK', 'NOK', 'not_checked');

-- generation_status enum: tracks the status of ai generation sessions
-- values:
--   - 'pending': generation in progress
--   - 'success': generation completed successfully
--   - 'error': generation failed
create type generation_status as enum ('pending', 'success', 'error');

