-- migration: create generations table
-- purpose: create table for tracking ai flashcard generation sessions
-- affected tables: generations
-- special considerations:
--   - tracks generation history with input text, model, and results
--   - supports daily generation limits (enforced at application layer)
--   - includes business logic validation (accepted <= generated)
--   - designed for automatic cleanup after 30 days (retention policy)

-- create generations table
-- stores history of ai flashcard generation sessions
create table generations (
    -- primary key: auto-incrementing bigint (session identifier)
    session_id bigint generated always as identity primary key,
    
    -- foreign key to supabase auth.users
    -- on delete cascade: deleting a user removes their generation history
    user_id uuid not null references auth.users(id) on delete cascade,
    
    -- hash of input text provided by user for generation
    input_text_hash text not null,

    -- length of original input text
    input_text_length integer not null,
    
    -- name/identifier of ai model used for generation
    -- required for analytics and debugging
    model text not null,
    
    -- current status of generation session
    -- defaults to 'pending' when session is created
    status generation_status not null default 'pending',
    
    -- total number of flashcards generated by ai
    -- defaults to 0, must be non-negative
    generated_total integer not null default 0 check (generated_total >= 0),
    
    -- number of generated flashcards accepted/saved by user
    -- defaults to 0, must be non-negative
    accepted_total integer not null default 0 check (accepted_total >= 0),
    
    -- timestamp: when generation session was created (utc)
    created_at timestamptz not null default now(),
    
    -- timestamp: when generation session was last updated (utc)
    updated_at timestamptz not null default now(),
    
    -- business logic constraint: accepted count cannot exceed generated count
    constraint accepted_lte_generated check (accepted_total <= generated_total)
);

-- index for fast lookup of user's generation sessions
-- supports queries like: select * from generations where user_id = ?
create index idx_generations_user_id on generations(user_id);

-- composite index for daily limit queries
-- supports queries filtering by user and sorting by creation time (descending)
-- useful for "generations in last 24 hours" queries
create index idx_generations_user_created on generations(user_id, created_at desc);

-- index for automatic cleanup of old records
-- supports retention policy: delete records older than 30 days
-- used by cleanup function (see separate migration)
create index idx_generations_created_at on generations(created_at);

-- enable row level security on generations table
-- ensures users can only access their own generation history
alter table generations enable row level security;

-- rls policy for select: users can only view their own generation sessions
-- applies to both authenticated and anonymous users (filtered by auth.uid())
create policy generations_select_policy on generations
    for select
    using (user_id = auth.uid());

-- rls policy for insert: users can only create generation sessions for themselves
-- with check ensures user_id in new row matches authenticated user
create policy generations_insert_policy on generations
    for insert
    with check (user_id = auth.uid());

-- rls policy for update: users can only modify their own generation sessions
-- using clause filters which rows can be updated
-- with check ensures updated row still belongs to the user
create policy generations_update_policy on generations
    for update
    using (user_id = auth.uid())
    with check (user_id = auth.uid());

-- rls policy for delete: users can only delete their own generation sessions
-- using clause filters which rows can be deleted
create policy generations_delete_policy on generations
    for delete
    using (user_id = auth.uid());

